
ALTER TABLE [dbo].[EMPLOYEE] ADD  
CONSTRAINT [FK_EMPLOYEE_BOFFICE_ID_BOffice] 
FOREIGN KEY([BOffice_ID])
REFERENCES [dbo].[BOFFICE] ([BOffice_ID])
GO


ALTER TABLE [dbo].[EMPLOYEE] CHECK 
CONSTRAINT [FK_EMPLOYEE_BOFFICE_ID_BOffice]
GO

ALTER TABLE [dbo].[ORDER_CHECK] ADD  
CONSTRAINT [FK_ORDER_CHECK_BOFFICE_BOffice_ID] 
FOREIGN KEY([BOffice])
REFERENCES [dbo].[BOFFICE] ([BOffice_ID])
GO


ALTER TABLE [dbo].[ORDER_CHECK] 
CHECK CONSTRAINT [FK_ORDER_CHECK_BOFFICE_BOffice_ID]
GO


ALTER TABLE [dbo].[ORDER_CHECK] ADD  
CONSTRAINT [FK_ORDER_CHECK_CUSTOMER_ID_Card] 
FOREIGN KEY([Customer_ID])
REFERENCES [dbo].[CUSTOMER] ([ID_Card])
GO

ALTER TABLE [dbo].[ORDER_CHECK] 
CHECK CONSTRAINT [FK_ORDER_CHECK_CUSTOMER_ID_Card]
GO

ALTER TABLE [dbo].[PRODUCT] ADD  
CONSTRAINT [FK_PRODUCT_BOFFICE_BOffice] 
FOREIGN KEY([BOffice])
REFERENCES [dbo].[BOFFICE] ([BOffice_ID])
GO

ALTER TABLE [dbo].[PRODUCT] 
CHECK CONSTRAINT [FK_PRODUCT_BOFFICE_BOffice]
GO


ALTER TABLE [dbo].[PRODUCT]  ADD  
CONSTRAINT [FK_PRODUCT_CATEGORY_ID_Category] 
FOREIGN KEY([ID_Category])
REFERENCES [dbo].[CATEGORY] ([ID_Category])
GO


ALTER TABLE [dbo].[PRODUCT] 
CHECK CONSTRAINT [FK_PRODUCT_CATEGORY_ID_Category]
GO


ALTER TABLE [dbo].[PRODUCT] ADD  
CONSTRAINT [FK_PRODUCT_SUPPLIER_ID_Supplier] 
FOREIGN KEY([ID_Supplier])
REFERENCES [dbo].[SUPPLIER] ([ID_Supplier])
GO


ALTER TABLE [dbo].[PRODUCT] 
CHECK CONSTRAINT [FK_PRODUCT_SUPPLIER_ID_Supplier]
GO


ALTER TABLE [dbo].[PURCHASE_ITEM]  ADD  
CONSTRAINT [FK_PURCHASE_ITEM_ORDER_CHECK_Invoice_ID] 
FOREIGN KEY([Invoice_ID])
REFERENCES [dbo].[ORDER_CHECK] ([Invoice_ID])
GO


ALTER TABLE [dbo].[PURCHASE_ITEM] 
CHECK CONSTRAINT [FK_PURCHASE_ITEM_ORDER_CHECK_Invoice_ID]
GO


ALTER TABLE [dbo].[PURCHASE_ITEM]  ADD  
CONSTRAINT [FK_PURCHASE_ITEM_PRODUCT_ID_Product] 
FOREIGN KEY([Product_ID])
REFERENCES [dbo].[PRODUCT] ([ID_Product])
GO


ALTER TABLE [dbo].[PURCHASE_ITEM] 
CHECK CONSTRAINT [FK_PURCHASE_ITEM_PRODUCT_ID_Product]
GO